

#         Powered by TabooLib 6.0         #


Logs:
  enable: false
  ignore:
    - org.bukkit.command.Command

Database:
  # LOCAL、SQL
  use: SQL
  source:
    SQL:
      host: localhost
      port: 3306
      user: root
      password: root
      database: test
      table: raphael