DatabaseMongo:
  enable: false
  client: mongodb://localhost:27001
  database: raphael
  collection: raphael

DatabaseSQL:
  enable: false
  host: ~
  port: 3306
  user: root
  password: root
  database: test
  table: raphael_database

Logs:
  enable: false
  ignore:
    - org.bukkit.command.Command